services:
  db:
    image: postgres:18-alpine
    container_name: aimonitoring_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aimonitoring
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

  web:
    build: .
    container_name: aimonitoring_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/aimonitoring  # 💡 localhost 대신 db 서비스명으로 접속
    volumes:
      - static_images:/app/static/images
    restart: always

volumes:
  postgres_data:
  static_images:
